{
    "name": "Employee Leave Management",
    "summary": "A complete employee leave management module for Odoo 18/19",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "depends": ["base", "mail", "hr"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/leave_type_data.xml",
        "data/email_template.xml",
        "data/cron.xml",
        "views/employee_views.xml",
        "views/leave_type_views.xml",
        "views/leave_request_views.xml",
        "views/leave_balance_views.xml",
        "views/dashboard_views.xml",
        "views/menus.xml",
        "wizard_views/leave_rejection_wizard_views.xml",
        "reports/leave_report.xml",
        "reports/leave_report_templates.xml",
    ],
    "demo": [
        "demo/demo.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
